%% %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Modified from  

%% Data loading & Figure Specs
clear all
% load('F0DL_03_Figures.mat');
global D G
% D:    Data
% G:    Graphics

%% Data Preparation: Waveform, Excitation Pattern, Cochleogram

% Sound
    D.F0 =              220;
    D.HN =              (1:70)';
    D.SR =              100000;
    D.Tseq =            (1:1:D.SR)/D.SR;
    D.Waveform =        1/length(D.HN) * sum(sin(...
                        2*pi*D.F0* D.HN*D.Tseq));
                    
% Cochlea Illustration
    D.CochleaImage =    imread('Cochlea_Illustration.PNG');
                
% Calculate the Auditory Filterbank
    D.FreqIn =          1:1:32000;
    D.FreqHout =        125*2.^(0:(1/48):log2(32000/125));
    for i = 1:length(D.HN)
        D.SpecHin{i} =  0 * D.FreqIn;
        D.SpecHin{i}(D.F0*i)= ...
                        1;
        D.SpecHout{i} = ...
                        HumanExcitationPattern(D.FreqIn, D.SpecHin{i}, D.FreqHout);
    end;

% Calculate the ERB
    D.FreqF0 =          220;
    D.FreqF0ERB =       24.7*(4.37*D.FreqF0/1000 +1);
    D.FreqF0ERBX =      [   D.FreqF0-D.FreqF0ERB/2  D.FreqF0+D.FreqF0ERB/2 ];
    D.FreqF0ERBY =      [   -30                     0];     
                
% Calculate the Excitation Pattern
    D.FreqIn =          1:1:32000;
    D.SpecALLin =       0 * D.FreqIn;
    D.SpecALLin(D.F0*(1:1:length(D.HN))) = ...
                        ones(1, length(D.HN));
    D.FreqALLout =      125*2.^(0:(1/48):log2(32000/125));
    D.SpecALLout =      HumanExcitationPattern(D.FreqIn, D.SpecALLin, D.FreqALLout);
    D.ExcPttnCut =      220*[7 16];
    D.ExcPttnFreqInx1 =	1:(find(D.FreqALLout<D.ExcPttnCut(1),1, 'last')+1);
    D.ExcPttnFreqInx2 =	find(D.FreqALLout<D.ExcPttnCut(1),1, 'last'):...
                        (find(D.FreqALLout<D.ExcPttnCut(2),1, 'last')+1);
    D.ExcPttnFreqInx3 =	find(D.FreqALLout<D.ExcPttnCut(2),1, 'last'):...
                        length(D.FreqALLout);
    D.ExcPttnALLx1 =	[D.FreqALLout(D.ExcPttnFreqInx1), fliplr(D.FreqALLout(D.ExcPttnFreqInx1))];
    D.ExcPttnALLy1 =    [D.SpecALLout(D.ExcPttnFreqInx1), -30*ones(1,length(D.ExcPttnFreqInx1))];  
    D.ExcPttnALLx2 =	[D.FreqALLout(D.ExcPttnFreqInx2), fliplr(D.FreqALLout(D.ExcPttnFreqInx2))];
    D.ExcPttnALLy2 =	[D.SpecALLout(D.ExcPttnFreqInx2), -30*ones(1,length(D.ExcPttnFreqInx2))]; 
    D.ExcPttnALLx3 =	[D.FreqALLout(D.ExcPttnFreqInx3), fliplr(D.FreqALLout(D.ExcPttnFreqInx3))];
    D.ExcPttnALLy3 =	[D.SpecALLout(D.ExcPttnFreqInx3), -30*ones(1,length(D.ExcPttnFreqInx3))]; 

% Calculate the Cochleogram
    D.freqrefHz =       220;
    D.freqrangeHz =     [90 22000];
    D.freqstepOct =     0.05;
    D.freqrangeOct =    round(log2(D.freqrangeHz/D.freqrefHz)/D.freqstepOct)*D.freqstepOct;
    % Determine the Central Frequencies of the Filter Bank (in Hz)
    D.cf =              D.freqrefHz * 2.^( D.freqrangeOct(1):D.freqstepOct:D.freqrangeOct(end) );
    D.Mat =             HumanCochleogram(D.Waveform(1:(D.SR*0.1)), D.SR, D.cf)';

%% Graphics Preparation: 
G.H0Mag =           3;

% Figure Cochlear
G.FigCoWidthS =     2;
G.FigCoHeightS =	0.1;
G.FigCoWidth =      NaN;
G.FigCoHeight =     NaN;
G.FigCoColumn =     1;

% Axes ALL
G.AxesAllWidth =    6.0;
G.AxesAllWidthS =   1.0;	% Start Gap
G.AxesAllWGap =     0.7;    % Gap
G.AxesAllWidthL =   0.2;    % Last Gap
G.AxesAll2WidthS =  G.AxesAllWidth + G.AxesAllWidthS + G.AxesAllWGap;
G.AxesAll2Width =   1.1;
G.AxesAllHeightL =	0.8;    % Last Gap
G.Axes1Height =     1.6;	G.Axes1HS =       0.45;
G.Axes2Height =     1;      G.Axes2HS =       0.45;
G.Axes3Height =     1.7;    G.Axes3HS =       0.45;
G.Axes4Height =     1.7;    G.Axes4HS =       0.45;
G.Axes5Height =     2.0;    G.Axes5HS =       0.9;
G.Axes2IWidth =     G.AxesAllWidth + G.AxesAllWGap + G.AxesAll2Width;
G.Axes2IHeight =    G.Axes2IWidth/size(D.CochleaImage,2)*size(D.CochleaImage,1);

G.Axes1Position =   [   G.AxesAllWidthS,    G.Axes5HS+G.Axes5Height+G.Axes4HS+G.Axes4Height+G.Axes3HS+G.Axes3Height+G.Axes2HS+G.Axes2Height+G.Axes1HS,...
                        G.AxesAllWidth,     G.Axes1Height]; 
G.Axes2Position =   [   G.AxesAllWidthS,    G.Axes5HS+G.Axes5Height+G.Axes4HS+G.Axes4Height+G.Axes3HS+G.Axes3Height+G.Axes2HS,...
                        G.AxesAllWidth,     G.Axes2Height]; 
G.Axes2IPosition =  [   G.AxesAllWidthS,    G.Axes5HS+G.Axes5Height+G.Axes4HS+G.Axes4Height+G.Axes3HS+G.Axes3Height+G.Axes2HS,...
                        G.Axes2IWidth,      G.Axes2IHeight]; 
G.Axes3Position =   [   G.AxesAllWidthS,    G.Axes5HS+G.Axes5Height+G.Axes4HS+G.Axes4Height+G.Axes3HS,...
                        G.AxesAllWidth,     G.Axes3Height]; 
G.Axes32Position =	[   G.AxesAll2WidthS,   G.Axes5HS+G.Axes5Height+G.Axes4HS+G.Axes4Height+G.Axes3HS,...
                        G.AxesAll2Width,	G.Axes3Height]; 
G.Axes4Position =   [   G.AxesAllWidthS,    G.Axes5HS+G.Axes5Height+G.Axes4HS,...
                        G.AxesAllWidth,     G.Axes4Height];  
G.Axes5Position =   [   G.AxesAllWidthS,    G.Axes5HS,...
                        G.AxesAllWidth,     G.Axes5Height];     
G.Axes52Position =	[   G.AxesAll2WidthS,   G.Axes5HS,...
                        G.AxesAll2Width,	G.Axes5Height];     
                  
G.FigCoWidth =      G.AxesAllWidthS +   G.AxesAllWidth + ...
                    G.AxesAllWGap +     G.AxesAll2Width + ...
                    G.AxesAllWidthL;
G.FigCoHeight =     G.Axes5HS + G.Axes5Height + ...
                    G.Axes4HS + G.Axes4Height + ...
                    G.Axes3HS + G.Axes3Height + ...
                    G.Axes2HS + G.Axes2Height + ...
                    G.Axes1HS + G.Axes1Height + G.AxesAllHeightL;
G.FigCoPosition =   [   G.FigCoWidthS,      G.FigCoHeightS,...
                        G.FigCoWidth,       G.FigCoHeight];
G.FigCoAxesXLim =   [90 22000];
G.FigCoAxesXLim2 =  [110 440];
G.AxesERBWidth =    G.Axes3Position(3)/...
                        log(G.FigCoAxesXLim(2)  /G.FigCoAxesXLim(1))*...
                        log(G.FigCoAxesXLim2(2) /G.FigCoAxesXLim2(1));
G.Axes32Position =  [   sum(G.Axes32Position([1 3]))-G.AxesERBWidth,G.Axes32Position(2),...
                        G.AxesERBWidth,                             G.Axes32Position(4)];
G.LineWidthS =      1.5;
G.AxesPartNumX =    -0.9;   % in cm
G.AxesPartNumX2 =   -0.05;
G.AxesPartNumX3 =   -0.45;
G.AxesPartNumYS =   [   0.6     0.25     0.25     0.25     0.25     0.25];
G.AxesPartNumY =    G.AxesPartNumYS + ...
                    [G.Axes1Height G.Axes2Height G.Axes3Height G.Axes4Height G.Axes5Height G.Axes5Height];
G.AxesTitleX =      -0.5;
G.AxesTitleX2 =      0.35;
G.AxesTitleX3 =     -0.05;

% T.AxesXTick             = [ 0.5 1 2 3 4 5 6 7 8 10 13 16 20 30 40 60];
% T.AxesXTickLabel        = '|1|2|3|4|5|6|7|8|10|13|16|20|30|40|60';
% T.AxesYTick1            = 10:20:70;
% T.AxesYTick2            = 1:1:4;
% T.AxesYTick2Label       = '4|3|2|1';
% 
% T.AxesYLim1             = [10 70];
% T.AxesYLim2             = [0 5];
% T.AxesYTickLabelXPosi2	= 0.78;
% T.AxesYLabelXPosi       = 0.48;
% T.AxesPartNumXposi      = -0.15;

%% Figure Cochlea
G.HH.hFigCo = figureStyled('Nature',...
            'Scaling',             	G.H0Mag,...
            'Position',           	G.FigCoPosition,...
            'Column',               G.FigCoColumn);
%% Draw the Cochlea Illustration first to put it at the bottom
G.HH.hFigCoAxes2I = axes(...
            'Parent',               G.HH.hFigCo,...
            'Position',             G.Axes2IPosition,...
            'Layer',                'bottom',...
            'Box',                  'off',...
            'Visible',              'off');
G.HH.hFigCoAxes2IImage = image( flipud(D.CochleaImage),...
            'Parent',               G.HH.hFigCoAxes2I); 
set(G.HH.hFigCoAxes2I,...
            'XLim',                 [0 size(D.CochleaImage,2)],...
            'YLim',                 [0 size(D.CochleaImage,1)] );

%% Spectrum
G.HH.hFigCoAxes1h = axes(...
            'Parent',               G.HH.hFigCo,...
            'Position',             G.Axes1Position,...
            'Color',                'none',...
            'XLim',                 [0 G.AxesAllWidth],...
            'YLim',                 [0 G.Axes1Height],...
            'XTick',                [],...
            'YTick',                []);
G.HH.hFigCoAxes1 = axes(...
            'Parent',               G.HH.hFigCo,...
            'Position',             G.Axes1Position,...
            'XAxisLocation',        'top',...
            'XScale',               'Log',...
            'XLim',                 G.FigCoAxesXLim,...
            'YLim',                 [0 1],...
            'YTick',                [0 1],...
            'XTickLabel',           {'100', '1,000', '10,000'},...
            'YTickLabel',           {'     '});
for i = 1:length(D.HN)
    plot(D.F0*i*ones(1,2), [0 0.8],...
            'Parent',               G.HH.hFigCoAxes1,...
            'LineWidth',            0.5); 
end
G.HH.hFigCoAxes1XLabel =  xlabel({'Frequency (Hz)'},...
            'Parent',               G.HH.hFigCoAxes1,...
         	'FontSize',             7,...
            'HorizontalAlignment',  'Center',...
            'VerticalAlignment',    'Baseline');
G.HH.hFigCoAxes1YLabel =  ylabel({'Level (a.u.)'},...
            'Parent',               G.HH.hFigCoAxes1,...
         	'FontSize',             7,...
            'VerticalAlignment',    'Bottom');
G.HH.hFigCoAxes1Part = text(G.AxesPartNumX, G.AxesPartNumY(1), 'a',...
            'Parent',               G.HH.hFigCoAxes1h,...
         	'FontSize',             8,...
         	'FontWeight',           'bold',...
         	'HorizontalAlignment',	'Left',...
         	'VerticalAlignment',	'Middle');
G.HH.hFigCoAxes1Title = text(G.AxesTitleX,  G.AxesPartNumY(1), 'Spectrum',...
            'Parent',               G.HH.hFigCoAxes1h,...
         	'FontSize',             7,...
         	'HorizontalAlignment',	'Left',...
         	'VerticalAlignment',	'Middle');
       
%% Cochlea
G.HH.hFigCoAxes2h = axes(...
            'Parent',               G.HH.hFigCo,...
            'Position',             G.Axes2Position,...
            'Color',                'none',...
            'Visible',              'off',...
            'XLim',                 [0 G.AxesAllWidth],...
            'YLim',                 [0 G.Axes2Height],...
            'XTick',                [],...
            'YTick',                []);
G.HH.hFigCoAxes2 = axes(...
            'Parent',               G.HH.hFigCo,...
            'Position',             G.Axes2Position,...
            'Visible',              'off',...
            'XScale',               'Log',...
            'XLim',                 G.FigCoAxesXLim,...
            'XTickLabel',           {},...
            'YTickLabel',           {'          '});
text(0,  0.6, {'Low frequency'},...
            'Parent',               G.HH.hFigCoAxes2h,...
         	'FontSize',             5,...
            'Color',                0.3*[1,1,1],...
         	'HorizontalAlignment',	'Left',...
         	'VerticalAlignment',	'Middle');
text(3.8,  0.6, {'High frequency'},...
            'Parent',               G.HH.hFigCoAxes2h,...
         	'FontSize',             5,...
            'Color',                0.3*[1,1,1],...
         	'HorizontalAlignment',	'Left',...
         	'VerticalAlignment',	'Middle');
G.HH.hFigCoAxes2Part = text(G.AxesPartNumX, G.AxesPartNumY(2), 'b',...
            'Parent',               G.HH.hFigCoAxes2h,...
         	'FontSize',             8,...
         	'FontWeight',           'bold',...
         	'HorizontalAlignment',	'Left',...
         	'VerticalAlignment',	'Middle');
G.HH.hFigCoAxes2Title = text(G.AxesTitleX,  G.AxesPartNumY(2), 'Cochlea, and uncoiled basilar membrane',...
            'Parent',               G.HH.hFigCoAxes2h,...
         	'FontSize',             7,...
         	'HorizontalAlignment',	'Left',...
         	'VerticalAlignment',	'Middle');
        
%% Auditory Filterbank
G.HH.hFigCoAxes3h = axes(...
            'Parent',               G.HH.hFigCo,...
            'Position',             G.Axes3Position,...
            'Color',                'none',...
            'XLim',                 [0 G.AxesAllWidth],...
            'YLim',                 [0 G.Axes3Height],...
            'XTick',                [],...
            'YTick',                []);
G.HH.hFigCoAxes3 = axes(...
            'Parent',               G.HH.hFigCo,...
            'Position',             G.Axes3Position,...
            'XScale',               'Log',...
            'XLim',                 G.FigCoAxesXLim,...
            'YLim',                 [-30 5],...
            'YTick',                [-20 -10 0],...
            'XTickLabel',           {});
for i = 1:length(D.HN)
    plot(D.FreqHout, D.SpecHout{i},...
            'Parent',               G.HH.hFigCoAxes3,...
            'LineWidth',            0.5); 
end
G.HH.hFigCoAxes3YLabel =  ylabel({'Level (dB)'},...
            'Parent',               G.HH.hFigCoAxes3,...
         	'FontSize',             7,...
            'VerticalAlignment',    'Bottom');
G.HH.hFigCoAxes3Part = text(G.AxesPartNumX, G.AxesPartNumY(3), 'c',...
            'Parent',               G.HH.hFigCoAxes3h,...
         	'FontSize',             8,...
         	'FontWeight',           'bold',...
         	'HorizontalAlignment',	'Left',...
         	'VerticalAlignment',	'Middle');
G.HH.hFigCoAxes3Title = text(G.AxesTitleX,  G.AxesPartNumY(3), 'Auditory filterbank',...
            'Parent',               G.HH.hFigCoAxes3h,...
         	'FontSize',             7,...
         	'HorizontalAlignment',	'Left',...
         	'VerticalAlignment',	'Middle');

%% ERB
G.HH.hFigCoAxes32h = axes(...
            'Parent',               G.HH.hFigCo,...
            'Position',             G.Axes32Position,...
            'Color',                'none',...
            'XLim',                 [0 G.AxesERBWidth],...
            'YLim',                 [0 G.Axes3Height],...
            'XTick',                [],...
            'YTick',                []);
G.HH.hFigCoAxes32 = axes(...
            'Parent',               G.HH.hFigCo,...
            'Position',             G.Axes32Position,...
            'XScale',               'Log',...
            'XTickLabel',           {},...
            'XLim',                 G.FigCoAxesXLim2,...
            'YLim',                 [-30 5],...
            'YTick',                {});
plot(D.FreqHout, D.SpecHout{1}, '-',...
            'Parent',               G.HH.hFigCoAxes32,...
            'LineWidth',            0.5,...
            'Color',                0.7*[1 1 1]); 
plot(D.FreqF0ERBX([1 1 2 2]), D.FreqF0ERBY([1 2 2 1]), '-',...
            'Parent',               G.HH.hFigCoAxes32,...
            'LineWidth',            0.5); 
G.HH.hFigCoAxes3Part = text(G.AxesPartNumX2, G.AxesPartNumY(3), 'd',...
            'Parent',               G.HH.hFigCoAxes32h,...
         	'FontSize',             8,...
         	'FontWeight',           'bold',...
         	'HorizontalAlignment',	'Left',...
         	'VerticalAlignment',	'Middle');
G.HH.hFigCoAxes3Title = text(G.AxesTitleX2,  G.AxesPartNumY(3), 'ERB',...
            'Parent',               G.HH.hFigCoAxes32h,...
         	'FontSize',             7,...
         	'HorizontalAlignment',	'Left',...
         	'VerticalAlignment',	'Middle');
        
        
%% Excitation Pattern
G.HH.hFigCoAxes4h = axes(...
            'Parent',               G.HH.hFigCo,...
            'Position',             G.Axes4Position,...
            'Color',                'none',...
            'XLim',                 [0 G.AxesAllWidth],...
            'YLim',                 [0 G.Axes4Height],...
            'XTick',                [],...
            'YTick',                []);
G.HH.hFigCoAxes4 = axes(...
            'Parent',               G.HH.hFigCo,...
            'Position',             G.Axes4Position,...
            'XScale',               'Log',...
            'XLim',                 G.FigCoAxesXLim,...
            'YLim',                 [-30 10],...
            'YTick',                [-20 -10 0],...
            'XTickLabel',           {});
G.HH.hFigCoAxes4YLabel =  ylabel({'Level (dB)'},...
            'Parent',               G.HH.hFigCoAxes4,...
         	'FontSize',             7,...
            'VerticalAlignment',    'Bottom');
    
% Excitation Pattern      
G.HH.hFigCoAxes4Fill1 = fill(D.ExcPttnALLx1, D.ExcPttnALLy1, [0 0.5 0],...
            'Parent',               G.HH.hFigCoAxes4,...
            'EdgeColor',            'none');
G.HH.hFigCoAxes4Fill2 = fill(D.ExcPttnALLx2, D.ExcPttnALLy2, [0 0.5 0],...
            'Parent',               G.HH.hFigCoAxes4,...
            'EdgeColor',            'none');
G.HH.hFigCoAxes4Fill3 = fill(D.ExcPttnALLx3, D.ExcPttnALLy3, [0 0 0.5],...
            'Parent',               G.HH.hFigCoAxes4,...
            'EdgeColor',            'none');        
set(G.HH.hFigCoAxes4Fill2,...
            'CData',                log2(get(G.HH.hFigCoAxes4Fill2, 'xdata')),...
            'FaceColor',            'interp');
colormap( G.HH.hFigCoAxes4,...
            [   zeros(256,1),...
                linspace(   0.5,    0,      256)',...
                linspace(   0,      0.5,    256)' ] );
text(500,	-20,	'Resolved',...
            'Parent',               G.HH.hFigCoAxes4,...
            'Color',                [1 1 1]);
text(4000,	-20,	'Unresolved',...
            'Parent',               G.HH.hFigCoAxes4,...
            'Color',                [1 1 1]);
G.HH.hFigCoAxes4Part = text(G.AxesPartNumX, G.AxesPartNumY(4), 'e',...
            'Parent',               G.HH.hFigCoAxes4h,...
         	'FontSize',             8,...
         	'FontWeight',           'bold',...
         	'HorizontalAlignment',	'Left',...
         	'VerticalAlignment',	'Middle');
G.HH.hFigCoAxes4Title = text(G.AxesTitleX,  G.AxesPartNumY(4), 'Excitation pattern',...
            'Parent',               G.HH.hFigCoAxes4h,...
         	'FontSize',             7,...
         	'HorizontalAlignment',	'Left',...
         	'VerticalAlignment',	'Middle');
        
%% Cochleogram
G.HH.hFigCoAxes5h = axes(...
            'Parent',               G.HH.hFigCo,...
            'Position',             G.Axes5Position,...
            'Color',                'none',...
            'XLim',                 [0 G.AxesAllWidth],...
            'YLim',                 [0 G.Axes5Height],...
            'XTick',                [],...
            'YTick',                []);
G.HH.hFigCoAxes5 = axes(...
            'Parent',               G.HH.hFigCo,...
            'Position',             G.Axes5Position,...
            'XScale',               'Log',...
            'XLim',                 G.FigCoAxesXLim,...
            'YTickLabel',           {});
G.HH.hFigCoAxes5Image = imagesc( max(1-1000*((D.Mat + abs(D.Mat)).^(2/1)), 0),...
            'Parent',               G.HH.hFigCoAxes5); 
set(gca,    'XLim',                 [0 length(D.cf)],...
            'YLim',                 round(D.SR/D.freqrefHz * [15.5 20.5]),...
            'YDir',                 'Reverse',...
            'XTick',                [],...
            'YTick',                round(D.SR/D.freqrefHz * 7.5),...
            'YTickLabel',           {'     '});
G.Cmap =    load('Fig1_CochleogramColorMap');
colormap(G.HH.hFigCoAxes5, G.Cmap.cmap);
G.HH.hFigCoAxes5ht = axes(...
            'Position',             G.Axes5Position,...
            'Color',                'none',...
            'XScale',               'log',...
            'YDir',                 'Reverse',...
            'XLim',                 G.FigCoAxesXLim,...
            'YLim',                 [0 5],...,...
            'YTick',                1:4,...
            'XTickLabel',           {'100', '1,000', '10,000'},...
            'YTickLabel',           {'   1', '   2', '   3', '   4'} );
G.HH.hFigCoAxes5XLabel =  xlabel({'Frequency (Hz)'},...
            'Parent',               G.HH.hFigCoAxes5ht,...
         	'FontSize',             7,...
            'HorizontalAlignment',  'Center',...
            'VerticalAlignment',    'Cap');
G.HH.hFigCoAxes5YLabel =  ylabel({'Time (cycle) \rightarrow'},...
            'Parent',               G.HH.hFigCoAxes5ht,...
         	'FontSize',             7,...
            'Rotation',             270,...
            'VerticalAlignment',    'Top');
G.HH.hFigCoAxes5Part = text(G.AxesPartNumX, G.AxesPartNumY(5), 'f',...
            'Parent',               G.HH.hFigCoAxes5h,...
         	'FontSize',             8,...
         	'FontWeight',           'bold',...
         	'HorizontalAlignment',	'Left',...
         	'VerticalAlignment',	'Middle');
G.HH.hFigCoAxes5Title = text(G.AxesTitleX,  G.AxesPartNumY(5), 'Cochleogram',...
            'Parent',               G.HH.hFigCoAxes5h,...
         	'FontSize',             7,...
         	'HorizontalAlignment',	'Left',...
         	'VerticalAlignment',	'Middle');      
        
%% Waveform
G.HH.hFigCoAxes52h = axes(...
            'Parent',               G.HH.hFigCo,...
            'Position',             G.Axes52Position,...
            'Color',                'none',...
            'Box',                  'off',...
            'XLim',                 [0 G.AxesAll2Width],...
            'YLim',                 [0 G.Axes5Height],...
            'XTick',                [],...
            'YTick',                [],...
            'XColor',               'none',...
            'YColor',               'none');
G.HH.hFigCoAxes52 = axes(...
            'Parent',               G.HH.hFigCo,...
            'Position',             G.Axes52Position,...
            'Box',                  'off',...
            'XLim',                 [min(D.Waveform) max(D.Waveform)],...
            'YLim',                 round(D.SR/D.freqrefHz * [15.5 20.5]),...
            'YDir',                 'Reverse',...
            'XTick',                [],...
            'YTick',                [],...
            'XColor',               'none',...
            'YColor',               'none');
G.HH.hFigCoAxes52Plot = plot(D.Waveform, 1:length(D.Waveform));
G.HH.hFigCoAxes52YLabel =  ylabel({'Time (cycle) \rightarrow'},...
            'Parent',               G.HH.hFigCoAxes52,...
         	'FontSize',             7,...
            'Rotation',             270,...
            'VerticalAlignment',    'Top',...
            'Color',                [0 0 0],...
            'Visible',              'on');
G.HH.hFigCoAxes52Part = text(G.AxesPartNumX3, G.AxesPartNumY(6), 'g',...
            'Parent',               G.HH.hFigCoAxes52h,...
         	'FontSize',             8,...
         	'FontWeight',           'bold',...
         	'HorizontalAlignment',	'Left',...
         	'VerticalAlignment',	'Middle');
G.HH.hFigCoAxes52Title = text(G.AxesTitleX3,  G.AxesPartNumY(6), 'Waveform',...
            'Parent',               G.HH.hFigCoAxes52h,...
         	'FontSize',             7,...
         	'HorizontalAlignment',	'Left',...
         	'VerticalAlignment',	'Middle');   
    